# Generated by Django 5.1.1 on 2024-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_quota",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quotarequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
